name: run-on-push-to-specific-branch
on: 
  push:
    branches:
      - 'feature'
      - 'story/**'
jobs: 
  push-job:
    runs-on: ubuntu-20.04
    steps: 
      - name: push msg
        run: echo "some output text on push to feature and story branch"
