name: my-workflow-with-multiple-jobs
on: [workflow_dispatch] # manual trigger
jobs: # must be plural
  my-first-job: # indented, belongs jo jobs, create your own job name
    runs-on: ubuntu-22.04 # pick a specific version, rather than 'latest' for things you rely on keeping working
    steps: 
      - name: Say hello
        run: echo "Hello World!!!"
  my-second-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Goodbye from job 2
        run: echo "Goodbye from job 2!!!"
