name: my-workflow-with-2-steps
on: [workflow_dispatch] # manual trigger
jobs: # must be plural
  my-first-job-with-steps: # indented, belongs to jobs, create your own job name
    runs-on: ubuntu-22.04 # pick a specific version, rather than 'latest' for things you rely on keeping working
    steps: 
      - name: Say hello
        run: echo "Hello World!!!"
      - name: Say goodbye
        run: echo "Goodbye World!!!"
